/*!CK:1988899782!*//*1433124584,*/

if (self.CavalryLogger) { CavalryLogger.start_js(["C\/SwS"]); }

__d("AdsInsightsSummaryLabels",[],function(a,b,c,d,e,f){b.__markCompiled&&b.__markCompiled();e.exports={};},null);
__d("AttachmentCTA",["Style"],function(a,b,c,d,e,f,g){b.__markCompiled&&b.__markCompiled();var h=10,i={init:function(j){var k=j.parentNode,l=Math.max(k.scrollHeight-j.scrollHeight-h*2,0);g.set(j,'margin-top',l+'px');}};e.exports=i;},null);
__d("BoostedPostSupportedTargeting",[],function(a,b,c,d,e,f){b.__markCompiled&&b.__markCompiled();var g={EDIT_TARGETING_FIELDS:['geo_locations','age_min','age_max','genders','interests','radius']};e.exports=g;},null);
__d("InputLabel.react",["React","cx","invariant","joinClasses"],function(a,b,c,d,e,f,g,h,i,j){b.__markCompiled&&b.__markCompiled();var k=g,l=k.PropTypes,m=0;function n(){return 'js_input_label_'+(m++);}var o=g.createClass({displayName:"InputLabel",propTypes:{display:l.oneOf(['block','inline'])},getDefaultProps:function(){return {display:'block'};},render:function(){i(this.props.children.length===2);var p=this.props.children[0],q=this.props.children[1],r=p.type==='input';p=g.cloneElement(p,{className:j(p.props.className,(("uiInputLabelInput")+(r&&p.props.type==='radio'?' '+"uiInputLabelRadio":'')+(r&&p.props.type==='checkbox'?' '+"uiInputLabelCheckbox":''))),id:p.props.id||n()});q=g.cloneElement(q,{className:j(q.props.className,'uiInputLabelLabel'),htmlFor:p.props.id});var s=(("uiInputLabel")+(' '+"clearfix")+(this.props.display==='inline'?' '+"inlineBlock":'')+(r?' '+"uiInputLabelLegacy":''));return (g.createElement("div",g.__spread({},this.props,{className:j(this.props.className,s)}),p,q));}});e.exports=o;},null);
__d("XUICardSection.react",["React","XUIBlock","cx","joinClasses"],function(a,b,c,d,e,f,g,h,i,j){b.__markCompiled&&b.__markCompiled();'use strict';var k=g.createClass({displayName:"XUICardSection",propTypes:h.propTypes,getDefaultProps:h.getDefaultProps,render:function(){var l=j("_4-u3",h.getBackgroundClass(this.props));return (g.createElement("div",g.__spread({},this.props,{className:j(this.props.className,l)}),this.props.children));}});e.exports=k;},null);
__d("AbstractCheckboxInput.react",["React","cx","invariant","joinClasses"],function(a,b,c,d,e,f,g,h,i,j){b.__markCompiled&&b.__markCompiled();var k=g,l=k.PropTypes,m=g.createClass({displayName:"AbstractCheckboxInput",propTypes:{tooltip:l.string},render:function(){i(!this.props.children||this.props.children.length===0);var n=j(this.props.className,"_kv1"),o=g.createElement("input",g.__spread({},this.props,{className:null,type:"checkbox"}),undefined);return (g.createElement("label",{className:n},o,g.createElement("span",{"data-hover":this.props.tooltip?'tooltip':null,"aria-label":this.props.tooltip})));}});e.exports=m;},null);
__d("XUICheckboxInput.react",["AbstractCheckboxInput.react","React","cx","joinClasses"],function(a,b,c,d,e,f,g,h,i,j){b.__markCompiled&&b.__markCompiled();var k=h.createClass({displayName:"XUICheckboxInput",render:function(){return (h.createElement(g,h.__spread({},this.props,{className:j(this.props.className,"_55sg")}),(void 0)));}});e.exports=k;},null);
__d("XUIAmbientNUXTheme",["cx"],function(a,b,c,d,e,f,g){b.__markCompiled&&b.__markCompiled();var h={wrapperClassName:"_2x6q",arrowDimensions:{offset:14,length:18}};e.exports=h;},null);
__d("XUIAmbientNUXBody.react",["React","XUICloseButton.react","cx","joinClasses"],function(a,b,c,d,e,f,g,h,i,j){b.__markCompiled&&b.__markCompiled();var k=g,l=k.PropTypes,m=g.createClass({displayName:"XUIAmbientNUXBody",propTypes:{onCloseButtonClick:l.func},render:function(){var n=j("_21es",this.props.className);return (g.createElement("div",{className:n},g.createElement(h,{shade:"light",className:"_36gl",onClick:this.props.onCloseButtonClick}),g.createElement("div",{className:"_36gn"},this.props.children)));}});e.exports=m;},null);
__d("XUIAmbientNUX.react",["HasLayerContextMixin","React","ReactLayer","ReactAbstractContextualDialog","XUIAmbientNUXTheme","XUIAmbientNUXBody.react"],function(a,b,c,d,e,f,g,h,i,j,k,l){b.__markCompiled&&b.__markCompiled();var m=h,n=m.PropTypes,o=300,p=380,q=i.createClass(j.createSpec({displayName:'XUIAmbientNUX',theme:k})),r=h.createClass({displayName:"XUIAmbientNUX",mixins:[g],propTypes:{alignment:n.oneOf(['left','center','right']),behaviors:n.object,context:n.object,contextRef:n.func,customwidth:n.number,offsetX:n.number,offsetY:n.number,onCloseButtonClick:n.func,position:n.oneOf(['above','below','left','right']),shown:n.bool,width:n.oneOf(['wide','normal','auto','custom'])},_getWidth:function(){switch(this.props.width){case 'wide':return p;case 'custom':return this.props.customwidth;case 'auto':return null;default:return o;}},render:function(){return (h.createElement(q,{alignment:this.props.alignment,autoFocus:false,behaviors:this.props.behaviors,context:this.getContextNode(),focusContextOnHide:false,offsetX:this.props.offsetX,offsetY:this.props.offsetY,position:this.props.position,shown:this.props.shown,width:this._getWidth(this.props)},h.createElement(l,{onCloseButtonClick:this.props.onCloseButtonClick},this.props.children)));}});e.exports=r;},null);
__d("XUIDialogSaveButton.react",["React","XUIDialogButton.react","fbt"],function(a,b,c,d,e,f,g,h,i){b.__markCompiled&&b.__markCompiled();var j=g.createClass({displayName:"XUIDialogSaveButton",render:function(){return (g.createElement(h,g.__spread({},this.props,{action:"confirm",label:i._("Save")})));}});e.exports=j;},null);
__d("ManagedError",[],function(a,b,c,d,e,f){b.__markCompiled&&b.__markCompiled();function g(h,i){Error.prototype.constructor.call(this,h);this.message=h;this.innerError=i;}g.prototype=new Error();g.prototype.constructor=g;e.exports=g;},null);
__d("getSafeBodyFromHTML",["UserAgent"],function(a,b,c,d,e,f,g){b.__markCompiled&&b.__markCompiled();var h=g.isBrowser('IE <= 9');function i(j){var k,l=null;if(!h&&document.implementation&&document.implementation.createHTMLDocument){k=document.implementation.createHTMLDocument('foo');k.documentElement.innerHTML=j;l=k.getElementsByTagName('body')[0];}return l;}e.exports=i;},null);
__d("GiftCredits",["AsyncRequest","Dialog","URI"],function(a,b,c,d,e,f,g,h,i){b.__markCompiled&&b.__markCompiled();var j={dialog:null,callback:null,purchaseLock:false,purchaseLockExpiryThreshold:5000,purchaseLockTimeoutId:null,getPurchaseCreditPrompt:function(k,l,m,n){j.main(k,null,null,null,m,null,null,null,'BuyCredits',{},n);},redeemGiftcard:function(k,l,m){var n=new i(document.location).setPath('/giftcards').toString();j.main(k,null,null,n,null,null,null,null,l,{},m);},getPrompt:function(k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,aa,ba,ca,da,ea,fa,ga,ha){j.main(k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,aa,ba,ca,da,ea,fa,ga,ha);},main:function(k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,aa,ba,ca,da,ea,fa,ga,ha){if(j.isPurchaseLocked())return false;j.setPurchaseLock(true);var ia={_path:'pay',method:'pay',display:'async',app_id:k,receiver:l,api_key:q,credits_purchase:x,action:s,next:n,dev_purchase_params:JSON.stringify(t),additional_params:JSON.stringify(u),order_info:JSON.stringify(m),product:v,package_id:w,request_id:y,sdk:z,quantity:aa,quantity_min:ba,quantity_max:ca,test_currency:da,pricepoint_id:ea,user:fa,user_hash:ga,ingame_gift_data:ha},ja=new g().setURI('/fbml/ajax/dialog/').setData(ia).setMethod('GET').setReadOnly(true).setStatusElement('commerce_get_more_loading');j.callback=o;j.dialog=new h().setAsync(ja).setModal(true).setCloseHandler(function(ka){j.setPurchaseLock(false);o(ka);}).show();},isPurchaseLocked:function(){return j.purchaseLock;},setPurchaseLock:function(k){j.purchaseLock=k;if(k){j.purchaseLockTimeoutId=setTimeout(function(){j.setPurchaseLock(false);},j.purchaseLockExpiryThreshold);}else clearTimeout(j.purchaseLockTimeoutId);return true;}};e.exports=j;},null);
__d("legacy:giftcredits",["GiftCredits"],function(a,b,c,d){b.__markCompiled&&b.__markCompiled();a.GiftCredits=b('GiftCredits');},3);
__d("isNumberLike",[],function(a,b,c,d,e,f){b.__markCompiled&&b.__markCompiled();function g(h){return !isNaN(parseFloat(h))&&isFinite(h);}e.exports=g;},null);
__d("TargetedPrivacyConsts",[],function(a,b,c,d,e,f){b.__markCompiled&&b.__markCompiled();var g={GENDER_BOTH:0,GENDER_MALE:1,GENDER_FEMALE:2,LOC_ALL:0,LOC_REGION:1,LOC_CITY:2};e.exports=g;},null);
__d("AssertionError",["ManagedError"],function(a,b,c,d,e,f,g){b.__markCompiled&&b.__markCompiled();function h(i){g.prototype.constructor.apply(this,arguments);}h.prototype=new g();h.prototype.constructor=h;e.exports=h;},null);
__d("Assert",["AssertionError","sprintf"],function(a,b,c,d,e,f,g,h){b.__markCompiled&&b.__markCompiled();function i(n,o){if(typeof n!=='boolean'||!n)throw new g(o);return n;}function j(n,o,p){var q;if(o===(void 0)){q='undefined';}else if(o===null){q='null';}else{var r=Object.prototype.toString.call(o);q=/\s(\w*)/.exec(r)[1].toLowerCase();}i(n.indexOf(q)!==-1,p||h('Expression is of type %s, not %s',q,n));return o;}function k(n,o,p){i(o instanceof n,p||'Expression not instance of type');return o;}function l(n,o){m['is'+n]=o;m['maybe'+n]=function(p,q){if(p!=null)o(p,q);};}var m={isInstanceOf:k,isTrue:i,isTruthy:function(n,o){return i(!!n,o);},type:j,define:function(n,o){n=n.substring(0,1).toUpperCase()+n.substring(1).toLowerCase();l(n,function(p,q){i(o(p),q);});}};['Array','Boolean','Date','Function','Null','Number','Object','Regexp','String','Undefined'].forEach(function(n){l(n,j.bind(null,n.toLowerCase()));});e.exports=m;},null);